#!/bin/bash

base_dir=$(dirname ${BASH_SOURCE})
command_name=$(basename ${BASH_SOURCE})

python_config_script=${base_dir}/lib/setup-python.sh
if [ -e ${python_config_script} ] ;then
  source ${python_config_script}
fi

python ${base_dir}/lib/gebp2fides.py "$@"
